export const metadata = {
  title: "Test Home Route",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue" }}>
          Header of Application
        </header>
        {children}
        <footer style={{ backgroundColor: "lightblue" }}>
          Footer of Application
        </footer>
      </body>
    </html>
  );
}
